/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messages.pb-c.h"
void   client_lizard_message__init
                     (ClientLizardMessage         *message)
{
  static const ClientLizardMessage init_value = CLIENT_LIZARD_MESSAGE__INIT;
  *message = init_value;
}
size_t client_lizard_message__get_packed_size
                     (const ClientLizardMessage *message)
{
  assert(message->base.descriptor == &client_lizard_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_lizard_message__pack
                     (const ClientLizardMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_lizard_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_lizard_message__pack_to_buffer
                     (const ClientLizardMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_lizard_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientLizardMessage *
       client_lizard_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientLizardMessage *)
     protobuf_c_message_unpack (&client_lizard_message__descriptor,
                                allocator, len, data);
}
void   client_lizard_message__free_unpacked
                     (ClientLizardMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_lizard_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client_roaches_message__init
                     (ClientRoachesMessage         *message)
{
  static const ClientRoachesMessage init_value = CLIENT_ROACHES_MESSAGE__INIT;
  *message = init_value;
}
size_t client_roaches_message__get_packed_size
                     (const ClientRoachesMessage *message)
{
  assert(message->base.descriptor == &client_roaches_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_roaches_message__pack
                     (const ClientRoachesMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_roaches_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_roaches_message__pack_to_buffer
                     (const ClientRoachesMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_roaches_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientRoachesMessage *
       client_roaches_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientRoachesMessage *)
     protobuf_c_message_unpack (&client_roaches_message__descriptor,
                                allocator, len, data);
}
void   client_roaches_message__free_unpacked
                     (ClientRoachesMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_roaches_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   remote_screen__init
                     (RemoteScreen         *message)
{
  static const RemoteScreen init_value = REMOTE_SCREEN__INIT;
  *message = init_value;
}
size_t remote_screen__get_packed_size
                     (const RemoteScreen *message)
{
  assert(message->base.descriptor == &remote_screen__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t remote_screen__pack
                     (const RemoteScreen *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &remote_screen__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t remote_screen__pack_to_buffer
                     (const RemoteScreen *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &remote_screen__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RemoteScreen *
       remote_screen__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RemoteScreen *)
     protobuf_c_message_unpack (&remote_screen__descriptor,
                                allocator, len, data);
}
void   remote_screen__free_unpacked
                     (RemoteScreen *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &remote_screen__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response_to_client__init
                     (ResponseToClient         *message)
{
  static const ResponseToClient init_value = RESPONSE_TO_CLIENT__INIT;
  *message = init_value;
}
size_t response_to_client__get_packed_size
                     (const ResponseToClient *message)
{
  assert(message->base.descriptor == &response_to_client__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response_to_client__pack
                     (const ResponseToClient *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response_to_client__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response_to_client__pack_to_buffer
                     (const ResponseToClient *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response_to_client__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ResponseToClient *
       response_to_client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ResponseToClient *)
     protobuf_c_message_unpack (&response_to_client__descriptor,
                                allocator, len, data);
}
void   response_to_client__free_unpacked
                     (ResponseToClient *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &response_to_client__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor client_lizard_message__field_descriptors[4] =
{
  {
    "msg_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ClientLizardMessage, msg_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ClientLizardMessage, has_code),
    offsetof(ClientLizardMessage, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ch",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ClientLizardMessage, ch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direction",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ClientLizardMessage, has_direction),
    offsetof(ClientLizardMessage, direction),
    &direction_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_lizard_message__field_indices_by_name[] = {
  2,   /* field[2] = ch */
  1,   /* field[1] = code */
  3,   /* field[3] = direction */
  0,   /* field[0] = msg_type */
};
static const ProtobufCIntRange client_lizard_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor client_lizard_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "client_lizard_message",
  "ClientLizardMessage",
  "ClientLizardMessage",
  "",
  sizeof(ClientLizardMessage),
  4,
  client_lizard_message__field_descriptors,
  client_lizard_message__field_indices_by_name,
  1,  client_lizard_message__number_ranges,
  (ProtobufCMessageInit) client_lizard_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor client_roaches_message__field_descriptors[4] =
{
  {
    "n_roaches",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ClientRoachesMessage, n_roaches),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_scores",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ClientRoachesMessage, n_r_scores),
    offsetof(ClientRoachesMessage, r_scores),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_direction",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ClientRoachesMessage, n_r_direction),
    offsetof(ClientRoachesMessage, r_direction),
    &direction_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_bool",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ClientRoachesMessage, n_r_bool),
    offsetof(ClientRoachesMessage, r_bool),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_roaches_message__field_indices_by_name[] = {
  0,   /* field[0] = n_roaches */
  3,   /* field[3] = r_bool */
  2,   /* field[2] = r_direction */
  1,   /* field[1] = r_scores */
};
static const ProtobufCIntRange client_roaches_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor client_roaches_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "client_roaches_message",
  "ClientRoachesMessage",
  "ClientRoachesMessage",
  "",
  sizeof(ClientRoachesMessage),
  4,
  client_roaches_message__field_descriptors,
  client_roaches_message__field_indices_by_name,
  1,  client_roaches_message__number_ranges,
  (ProtobufCMessageInit) client_roaches_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor remote_screen__field_descriptors[10] =
{
  {
    "msg_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RemoteScreen, msg_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ch",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RemoteScreen, ch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "old_x",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RemoteScreen, has_old_x),
    offsetof(RemoteScreen, old_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "old_y",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RemoteScreen, has_old_y),
    offsetof(RemoteScreen, old_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "new_x",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RemoteScreen, has_new_x),
    offsetof(RemoteScreen, new_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "new_y",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RemoteScreen, has_new_y),
    offsetof(RemoteScreen, new_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "score",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RemoteScreen, has_score),
    offsetof(RemoteScreen, score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "old_direction",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(RemoteScreen, has_old_direction),
    offsetof(RemoteScreen, old_direction),
    &direction_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "new_direction",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(RemoteScreen, has_new_direction),
    offsetof(RemoteScreen, new_direction),
    &direction_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "screen_roaches",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RemoteScreen, n_screen_roaches),
    offsetof(RemoteScreen, screen_roaches),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned remote_screen__field_indices_by_name[] = {
  1,   /* field[1] = ch */
  0,   /* field[0] = msg_type */
  8,   /* field[8] = new_direction */
  4,   /* field[4] = new_x */
  5,   /* field[5] = new_y */
  7,   /* field[7] = old_direction */
  2,   /* field[2] = old_x */
  3,   /* field[3] = old_y */
  6,   /* field[6] = score */
  9,   /* field[9] = screen_roaches */
};
static const ProtobufCIntRange remote_screen__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor remote_screen__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "remote_screen",
  "RemoteScreen",
  "RemoteScreen",
  "",
  sizeof(RemoteScreen),
  10,
  remote_screen__field_descriptors,
  remote_screen__field_indices_by_name,
  1,  remote_screen__number_ranges,
  (ProtobufCMessageInit) remote_screen__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response_to_client__field_descriptors[4] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ResponseToClient, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ResponseToClient, has_code),
    offsetof(ResponseToClient, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "assigned_char",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ResponseToClient, has_assigned_char),
    offsetof(ResponseToClient, assigned_char),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "score",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ResponseToClient, has_score),
    offsetof(ResponseToClient, score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response_to_client__field_indices_by_name[] = {
  2,   /* field[2] = assigned_char */
  1,   /* field[1] = code */
  3,   /* field[3] = score */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange response_to_client__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor response_to_client__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "response_to_client",
  "ResponseToClient",
  "ResponseToClient",
  "",
  sizeof(ResponseToClient),
  4,
  response_to_client__field_descriptors,
  response_to_client__field_indices_by_name,
  1,  response_to_client__number_ranges,
  (ProtobufCMessageInit) response_to_client__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue direction_t__enum_values_by_number[4] =
{
  { "UP", "DIRECTION_T__UP", 0 },
  { "DOWN", "DIRECTION_T__DOWN", 1 },
  { "LEFT", "DIRECTION_T__LEFT", 2 },
  { "RIGHT", "DIRECTION_T__RIGHT", 3 },
};
static const ProtobufCIntRange direction_t__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex direction_t__enum_values_by_name[4] =
{
  { "DOWN", 1 },
  { "LEFT", 2 },
  { "RIGHT", 3 },
  { "UP", 0 },
};
const ProtobufCEnumDescriptor direction_t__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "direction_t",
  "direction_t",
  "DirectionT",
  "",
  4,
  direction_t__enum_values_by_number,
  4,
  direction_t__enum_values_by_name,
  1,
  direction_t__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
